spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.100:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  redis:
    host: 192.168.1.100
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0